######################################################################
# Automatically generated by qmake (2.01a) K juuli 9 11:42:00 2008
######################################################################

TEMPLATE = app
QT += sql
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += TrayIcon.h
SOURCES += main.cpp TrayIcon.cpp
